### ISSUE TITLE
Evaluation: FileNotFoundError: [Errno 2] No such file or directory: './results/video_tef-vlen600_slowfast/opt.json'

### ISSUE THREAD

**Issue by maximotus** [NNNNAI/Ego4d_NLQ_2022_1st_Place_Solution#2]
Hi,

could you provide the opt.json file that comes along with the already provided model weights `./results/video_tef-vlen600_slowfast/model_0146.ckpt`?

```
$ python -m ms_cm.inference_ego4d_slowfast --resume ./results/video_tef-vlen600_slowfast/model_0146.ckpt --split val
Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2023-11-16 08:52:23.084:INFO:__main__ - Setup config, data and model...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/reler/ms_cm/inference_ego4d_slowfast.py", line 291, in <module>
    start_inference()
  File "/reler/ms_cm/inference_ego4d_slowfast.py", line 210, in start_inference
    opt = TestOptions().parse()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/reler/ms_cm/configs.py", line 250, in parse
    saved_options = load_json(os.path.join(opt.model_dir, self.saved_option_filename))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/utils/basic_utils.py", line 21, in load_json
    with open(filename, "r") as f:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './results/video_tef-vlen600_slowfast/opt.json'
```

Thanks a lot! 😄 

Best,
Maximotus

**Comment by NNNNAI** [comment]
Hello, thanks for your attention to ours work. It seems like I forget to upload the opt.json last year. I already leave that company so I can't reproduce the results. If you got the training data, you can train it again, it won't take too long. Or you could just make a fake opt.json according to the code. If you have any question, feel free to concat me, have a nice day~

Best,
Nick

**Comment by maximotus** [comment]
```
{
    "results_root": "results",
    "exp_id": "vlen600_slowfast",
    "seed": 2018,
    "device": 0,
    "num_workers": 8,
    "no_pin_memory": false,
    "lr": 0.0001,
    "lr_drop": 400,
    "wd": 0.0001,
    "n_epoch": 200,
    "max_es_cnt": 200,
    "bsz": 32,
    "eval_bsz": 100,
    "grad_clip": 0.1,
    "eval_untrained": false,
    "resume": null,
    "resume_all": false,
    "start_epoch": null,
    "max_q_l": 32,
    "max_v_l": 600,
    "clip_length": 2,
    "max_windows": 5,
    "no_norm_vfeat": false,
    "no_norm_tfeat": false,
    "v_feat_dirs": [
        "../episodic-memory/NLQ/VSLNet/data/features/nlq_official_v1/official",
        "./CLIP_feature_slowfast/Slowfast_vitb16CLIP_videofeature"
    ],
    "t_feat_dir": "./CLIP_feature_slowfast/Slowfast_vitb16CLIP_textfeature",
    "v_feat_dim": 2816,
    "t_feat_dim": 512,
    "ctx_mode": "video_tef",
    "position_embedding": "sine",
    "onlyv_layers": 2,
    "enc_layers": 0,
    "dec_layers": 2,
    "dim_feedforward": 1024,
    "hidden_dim": 256,
    "input_dropout": 0.5,
    "dropout": 0.1,
    "txt_drop_ratio": 0,
    "use_txt_pos": false,
    "nheads": 8,
    "num_queries": 10,
    "pre_norm": false,
    "n_input_proj": 2,
    "contrastive_hdim": 64,
    "temperature": 0.07,
    "lw_saliency": 1.0,
    "lw_highlight": 20.0,
    "lw_npm": 1.0,
    "lw_start_end": 1,
    "video_frame_contrastive_loss_coef": 1.0,
    "saliency_margin": 0.2,
    "aux_loss": false,
    "video_frame_contrastive_loss": true,
    "vsldataset_task": "nlq_official_v1",
    "vsldataset_fv": "official",
    "vsldataset_num_workers": 32,
    "vslnet_datapath": "../episodic-memory/NLQ/VSLNet/data/",
    "vslnet_thres_in_train": 0,
    "vslnet_dataset_save_dir": "./vslnet_dataset_savepath",
    "eval_gt_json": "../episodic-memory/NLQ/VSLNet/data/nlq_val.json",
    "conditioned_span_pred_num_heads": 8,
    "conditioned_span_pred_drop_rate": 0.2,
    "conditioned_span_pred_predictor": "bert",
    "num_cross_encoder_layers": 3,
    "cross_text_use_ori": false,
    "cross_input_dropout": 0.1,
    "cross_first": true,
    "v_hidden_size": 256,
    "hidden_size": 256,
    "v_hidden_act": "gelu",
    "hidden_act": "gelu",
    "v_intermediate_size": 1024,
    "intermediate_size": 1024,
    "v_hidden_dropout_prob": 0.1,
    "hidden_dropout_prob": 0.1,
    "bi_num_attention_heads": 8,
    "bi_hidden_size": 256,
    "v_target_size": 2818,
    "v_attention_probs_dropout_prob": 0.1,
    "attention_probs_dropout_prob": 0.1,
    "warmup_proportion": 0.1,
    "ego4d_train_num": 11296,
    "optim_name": "AdamW",
    "numscale_list": [
        2,
        3,
        4,
        5,
        6
    ],
    "allscaletopk": 2,
    "NPM_score_norm": 0,
    "use_sw": 1,
    "sw_len_ratio": [
        0.4,
        0.8
    ],
    "use_vs": 1,
    "vs_prob": 0.5,
    "preds_list": null,
    "results_dir": "results/video_tef-vlen600_slowfast"
}
```
